-- Append-oriented field-level verification history for songs.
-- This records who checked a snapshot value independently from the existing
-- confirmed / uncertain / unverified status columns on public.songs.

begin;

create table public.song_field_checks (
  id bigint generated by default as identity primary key,
  song_id bigint not null references public.songs (id) on delete cascade,
  field_name text not null,
  checked_value jsonb not null,
  checker_type text not null,
  evidence jsonb not null default '[]'::jsonb,
  note text,
  checked_at timestamptz not null default now(),
  constraint song_field_checks_field_name_check
    check (btrim(field_name) <> ''),
  constraint song_field_checks_checker_type_check
    check (checker_type ~ '^[a-z][a-z0-9_]*$'),
  constraint song_field_checks_evidence_array_check
    check (coalesce(jsonb_typeof(evidence) = 'array', false))
);

comment on table public.song_field_checks is
  'Append-oriented history of AI, human, and future checker reviews of individual songs fields.';

comment on column public.song_field_checks.checked_value is
  'JSON snapshot of the checked songs field value. Use the JSON literal null to record a check of a NULL value.';

comment on column public.song_field_checks.checker_type is
  'Checker category. Canonical initial values are ai and human; lowercase snake_case allows future categories.';

comment on column public.song_field_checks.evidence is
  'JSON array of evidence objects. Objects may contain source_type, url, label, and future source metadata.';

create index song_field_checks_song_field_checked_at_idx
  on public.song_field_checks (song_id, field_name, checked_at desc, id desc);

-- Management-only provenance. RLS is enabled without any anon or
-- authenticated policy, and public Data API privileges are explicitly removed.
alter table public.song_field_checks enable row level security;

revoke all privileges on table public.song_field_checks
  from anon, authenticated;

grant all privileges on table public.song_field_checks
  to service_role;

grant usage, select on sequence public.song_field_checks_id_seq
  to service_role;

commit;
