-- REVIEWED DRAFT — do not apply to Supabase in this task.
--
-- Additive exact-version model. Existing songs.version_type and original_*
-- columns remain authoritative until an approved, reviewed backfill switches
-- individual UI reads to these fields.

begin;

alter table public.songs
  add column performance_context text,
  add column version_kind text;

alter table public.songs
  add constraint songs_performance_context_check
    check (performance_context is null or performance_context in ('studio', 'live', 'other')),
  add constraint songs_version_kind_check
    check (version_kind is null or btrim(version_kind) <> '');

comment on column public.songs.performance_context is
  'Exact-version performance context. Proposed values: studio, live, or other. NULL means not yet migrated.';
comment on column public.songs.version_kind is
  'Short, application-controlled version classification. Initial preferred values are standard, rearranged, acoustic, solo, multilingual, alternate, and other. Free text at the DB layer avoids freezing the vocabulary.';

create index songs_performance_context_idx
  on public.songs (performance_context)
  where performance_context is not null;

create index songs_version_kind_idx
  on public.songs (version_kind)
  where version_kind is not null;

create table public.song_credits (
  id bigint generated by default as identity primary key,
  song_id bigint not null references public.songs (id) on delete cascade,
  role text not null,
  credit_name text not null,
  sort_order integer not null default 1,
  note text,
  created_at timestamptz not null default now(),
  constraint song_credits_role_check
    check (btrim(role) <> ''),
  constraint song_credits_credit_name_check
    check (btrim(credit_name) <> ''),
  constraint song_credits_sort_order_check
    check (sort_order > 0),
  constraint song_credits_song_role_order_unique
    unique (song_id, role, sort_order),
  constraint song_credits_song_role_name_unique
    unique (song_id, role, credit_name)
);

comment on table public.song_credits is
  'Exact songs.id/version credits. Initial role vocabulary is vocal, lyricist, composer, arranger; text allows future roles such as translator, additional_lyrics, producer, remix, and other.';
comment on column public.song_credits.credit_name is
  'Display-preserving credited name. This is intentionally not yet a creator-master foreign key.';

create index song_credits_song_role_idx
  on public.song_credits (song_id, role, sort_order, id);

create index song_credits_credit_name_idx
  on public.song_credits (credit_name);

-- Exact credits are introduced as management-only data. A future public UI
-- migration may add a read policy after data and presentation are reviewed.
alter table public.song_credits enable row level security;

revoke all privileges on table public.song_credits
  from anon, authenticated;

grant all privileges on table public.song_credits
  to service_role;

grant usage, select on sequence public.song_credits_id_seq
  to service_role;

commit;
