-- REVIEWED DRAFT — do not apply to Supabase in this task.
--
-- Keep song_field_checks and its source relation untouched. These additive,
-- entity-specific histories preserve foreign keys without introducing a
-- polymorphic target relation.

begin;

create table public.song_group_field_checks (
  id bigint generated by default as identity primary key,
  song_group_id bigint not null references public.song_groups (id) on delete cascade,
  field_name text not null,
  checked_value jsonb,
  checker_type text not null,
  evidence jsonb not null default '[]'::jsonb,
  note text,
  checked_at timestamptz not null default now(),
  constraint song_group_field_checks_field_name_check
    check (btrim(field_name) <> ''),
  constraint song_group_field_checks_checker_type_check
    check (checker_type ~ '^[a-z][a-z0-9_]*$'),
  constraint song_group_field_checks_evidence_array_check
    check (coalesce(jsonb_typeof(evidence) = 'array', false))
);

comment on table public.song_group_field_checks is
  'Append-only AI, human, and future checks of work-level song_groups fields. SQL NULL checked_value means the checked group field was NULL.';

create index song_group_field_checks_group_field_checked_at_idx
  on public.song_group_field_checks (song_group_id, field_name, checked_at desc, id desc);

create table public.song_credit_checks (
  id bigint generated by default as identity primary key,
  song_credit_id bigint not null references public.song_credits (id) on delete cascade,
  checked_value jsonb not null,
  checker_type text not null,
  evidence jsonb not null default '[]'::jsonb,
  note text,
  checked_at timestamptz not null default now(),
  constraint song_credit_checks_checker_type_check
    check (checker_type ~ '^[a-z][a-z0-9_]*$'),
  constraint song_credit_checks_evidence_array_check
    check (coalesce(jsonb_typeof(evidence) = 'array', false))
);

comment on table public.song_credit_checks is
  'Append-only checks of an exact song_credits row. checked_value snapshots role, credit_name, and sort_order so changed credits become stale automatically.';

create index song_credit_checks_credit_checked_at_idx
  on public.song_credit_checks (song_credit_id, checked_at desc, id desc);

create table public.song_group_field_check_sources (
  id bigint generated by default as identity primary key,
  song_group_field_check_id bigint not null
    references public.song_group_field_checks (id) on delete cascade,
  reference_source_id bigint not null
    references public.reference_sources (id) on delete restrict,
  locator text,
  evidence_note text,
  sort_order integer,
  created_at timestamptz not null default now(),
  constraint song_group_field_check_sources_unique
    unique (song_group_field_check_id, reference_source_id),
  constraint song_group_field_check_sources_sort_order_check
    check (sort_order is null or sort_order > 0)
);

create table public.song_credit_check_sources (
  id bigint generated by default as identity primary key,
  song_credit_check_id bigint not null
    references public.song_credit_checks (id) on delete cascade,
  reference_source_id bigint not null
    references public.reference_sources (id) on delete restrict,
  locator text,
  evidence_note text,
  sort_order integer,
  created_at timestamptz not null default now(),
  constraint song_credit_check_sources_unique
    unique (song_credit_check_id, reference_source_id),
  constraint song_credit_check_sources_sort_order_check
    check (sort_order is null or sort_order > 0)
);

create index song_group_field_check_sources_check_idx
  on public.song_group_field_check_sources (song_group_field_check_id);
create index song_group_field_check_sources_source_idx
  on public.song_group_field_check_sources (reference_source_id);
create index song_credit_check_sources_check_idx
  on public.song_credit_check_sources (song_credit_check_id);
create index song_credit_check_sources_source_idx
  on public.song_credit_check_sources (reference_source_id);

alter table public.song_group_field_checks enable row level security;
alter table public.song_credit_checks enable row level security;
alter table public.song_group_field_check_sources enable row level security;
alter table public.song_credit_check_sources enable row level security;

revoke all privileges on table
  public.song_group_field_checks,
  public.song_credit_checks,
  public.song_group_field_check_sources,
  public.song_credit_check_sources
from anon, authenticated;

grant all privileges on table
  public.song_group_field_checks,
  public.song_credit_checks,
  public.song_group_field_check_sources,
  public.song_credit_check_sources
to service_role;

grant usage, select on sequence
  public.song_group_field_checks_id_seq,
  public.song_credit_checks_id_seq,
  public.song_group_field_check_sources_id_seq,
  public.song_credit_check_sources_id_seq
to service_role;

commit;
