-- REVIEWED DRAFT — do not apply to Supabase in this task.
--
-- Entity master and durable relationships. Exact-version participation is
-- deliberately introduced separately so a group membership never asserts that
-- every member sang a particular version.

begin;

create table public.entities (
  id bigint generated by default as identity primary key,
  canonical_name text not null unique,
  entity_type text not null,
  note text,
  created_at timestamptz not null default now(),
  constraint entities_canonical_name_check check (btrim(canonical_name) <> ''),
  constraint entities_entity_type_check check (btrim(entity_type) <> '')
);

comment on table public.entities is
  'Named artists, groups, characters, voicebanks, projects, and other credited entities. entity_type is flexible text; recommended initial values are artist, group, character, voicebank, project, and other.';

create table public.entity_aliases (
  id bigint generated by default as identity primary key,
  entity_id bigint not null references public.entities (id) on delete cascade,
  alias_name text not null,
  note text,
  created_at timestamptz not null default now(),
  constraint entity_aliases_alias_name_check check (btrim(alias_name) <> ''),
  constraint entity_aliases_entity_alias_unique unique (entity_id, alias_name)
);

comment on table public.entity_aliases is
  'Alternative display or search names. An alias is intentionally not globally unique: ambiguous names must not be auto-resolved.';

create index entity_aliases_alias_name_idx on public.entity_aliases (alias_name);

create table public.entity_relationships (
  id bigint generated by default as identity primary key,
  subject_entity_id bigint not null references public.entities (id) on delete restrict,
  relationship_type text not null,
  object_entity_id bigint not null references public.entities (id) on delete restrict,
  valid_from date,
  valid_to date,
  sort_order integer,
  note text,
  created_at timestamptz not null default now(),
  constraint entity_relationships_type_check check (btrim(relationship_type) <> ''),
  constraint entity_relationships_distinct_entities_check check (subject_entity_id <> object_entity_id),
  constraint entity_relationships_dates_check check (valid_to is null or valid_from is null or valid_from <= valid_to),
  constraint entity_relationships_sort_order_check check (sort_order is null or sort_order > 0)
);

comment on table public.entity_relationships is
  'Directed entity relationships, such as group --member--> artist and character --voiced_by--> artist. These are normal relationships, not assertions of exact-version participation.';

create unique index entity_relationships_current_unique
  on public.entity_relationships (subject_entity_id, relationship_type, object_entity_id)
  where valid_from is null and valid_to is null;
create index entity_relationships_subject_type_idx
  on public.entity_relationships (subject_entity_id, relationship_type, sort_order, id);
create index entity_relationships_object_type_idx
  on public.entity_relationships (object_entity_id, relationship_type, id);

alter table public.entities enable row level security;
alter table public.entity_aliases enable row level security;
alter table public.entity_relationships enable row level security;

revoke all privileges on table
  public.entities,
  public.entity_aliases,
  public.entity_relationships
from anon, authenticated;

grant all privileges on table
  public.entities,
  public.entity_aliases,
  public.entity_relationships
to service_role;

grant usage, select on sequence
  public.entities_id_seq,
  public.entity_aliases_id_seq,
  public.entity_relationships_id_seq
to service_role;

commit;
