-- REVIEWED DRAFT — do not apply to Supabase in this task.
--
-- Structured official credits and actual exact-version participants. Credit
-- text remains mandatory even when a safe entity resolution is available.

begin;

create table public.song_group_credits (
  id bigint generated by default as identity primary key,
  song_group_id bigint not null references public.song_groups (id) on delete cascade,
  role text not null,
  credit_name text not null,
  entity_id bigint references public.entities (id) on delete set null,
  sort_order integer not null default 1,
  note text,
  created_at timestamptz not null default now(),
  constraint song_group_credits_role_check check (btrim(role) <> ''),
  constraint song_group_credits_credit_name_check check (btrim(credit_name) <> ''),
  constraint song_group_credits_sort_order_check check (sort_order > 0),
  constraint song_group_credits_group_role_order_unique unique (song_group_id, role, sort_order),
  constraint song_group_credits_group_role_name_unique unique (song_group_id, role, credit_name)
);

comment on table public.song_group_credits is
  'Underlying-work credits. credit_name preserves source text; entity_id is nullable because parsing or identity resolution can be ambiguous.';

create index song_group_credits_group_role_idx
  on public.song_group_credits (song_group_id, role, sort_order, id);
create index song_group_credits_entity_idx
  on public.song_group_credits (entity_id) where entity_id is not null;

alter table public.song_credits
  add column entity_id bigint references public.entities (id) on delete set null;

comment on column public.song_credits.entity_id is
  'Optional resolution of the preserved song_credits.credit_name to an entity. NULL means unresolved or intentionally not normalized.';

create index song_credits_entity_idx
  on public.song_credits (entity_id) where entity_id is not null;

create table public.song_participations (
  id bigint generated by default as identity primary key,
  song_id bigint not null references public.songs (id) on delete cascade,
  entity_id bigint not null references public.entities (id) on delete restrict,
  participation_role text not null default 'vocal',
  sort_order integer not null default 1,
  note text,
  created_at timestamptz not null default now(),
  constraint song_participations_role_check check (btrim(participation_role) <> ''),
  constraint song_participations_sort_order_check check (sort_order > 0),
  constraint song_participations_song_entity_role_unique unique (song_id, entity_id, participation_role),
  constraint song_participations_song_role_order_unique unique (song_id, participation_role, sort_order)
);

comment on table public.song_participations is
  'Actual entities participating in an exact songs.id version. This is authoritative over group membership for participant queries; it is distinct from official song_credits.';

create index song_participations_song_role_idx
  on public.song_participations (song_id, participation_role, sort_order, id);
create index song_participations_entity_role_idx
  on public.song_participations (entity_id, participation_role, song_id);

alter table public.song_group_credits enable row level security;
alter table public.song_participations enable row level security;

revoke all privileges on table
  public.song_group_credits,
  public.song_participations
from anon, authenticated;

grant all privileges on table
  public.song_group_credits,
  public.song_participations
to service_role;

grant usage, select on sequence
  public.song_group_credits_id_seq,
  public.song_participations_id_seq
to service_role;

commit;
