-- REVIEWED DRAFT — do not apply to Supabase in this task.
--
-- base_song_id was populated from a structural primary+standard heuristic. Do
-- not overload it as historical origin. These additive fields separate a
-- useful same-group metadata reference from an explicit origin assertion.

begin;

alter table public.song_groups
  add column metadata_reference_song_id bigint
    references public.songs (id) on delete restrict;

comment on column public.song_groups.base_song_id is
  'Legacy transitional reference populated by the primary+standard heuristic. It must not be interpreted as a historical origin assertion.';
comment on column public.song_groups.metadata_reference_song_id is
  'Optional same-group exact version useful for metadata comparison or inheritance. It is distinct from historical origin and from is_primary_version.';

create index song_groups_metadata_reference_song_idx
  on public.song_groups (metadata_reference_song_id)
  where metadata_reference_song_id is not null;

create table public.song_group_origins (
  id bigint generated by default as identity primary key,
  song_group_id bigint not null unique references public.song_groups (id) on delete cascade,
  origin_kind text not null,
  origin_song_id bigint references public.songs (id) on delete restrict,
  origin_reference_text text,
  note text,
  created_at timestamptz not null default now(),
  constraint song_group_origins_kind_check check (btrim(origin_kind) <> ''),
  constraint song_group_origins_reference_text_check check (origin_reference_text is null or btrim(origin_reference_text) <> ''),
  constraint song_group_origins_shape_check check (
    (origin_kind = 'internal_song' and origin_song_id is not null)
    or (origin_kind <> 'internal_song' and origin_song_id is null)
  )
);

comment on table public.song_group_origins is
  'Explicit historical-origin assertion for a work. Recommended values: internal_song and external_preexisting. Omit the row rather than recording unknown. origin_reference_text preserves an external source/work label without requiring a separate external-work master.';

create index song_group_origins_origin_song_idx
  on public.song_group_origins (origin_song_id)
  where origin_song_id is not null;

create function public.enforce_song_group_reference_membership()
returns trigger
language plpgsql
as $$
begin
  if tg_table_name = 'song_groups' then
    if new.metadata_reference_song_id is not null and not exists (
      select 1 from public.songs as song
      where song.id = new.metadata_reference_song_id
        and song.song_group_id = new.id
    ) then
      raise exception 'song_groups.metadata_reference_song_id % must belong to song_group %', new.metadata_reference_song_id, new.id;
    end if;
    return new;
  end if;

  if tg_table_name = 'song_group_origins' then
    if new.origin_song_id is not null and not exists (
      select 1 from public.songs as song
      where song.id = new.origin_song_id
        and song.song_group_id = new.song_group_id
    ) then
      raise exception 'song_group_origins.origin_song_id % must belong to song_group %', new.origin_song_id, new.song_group_id;
    end if;
    return new;
  end if;

  if tg_table_name = 'songs' and new.song_group_id is distinct from old.song_group_id then
    if exists (
      select 1 from public.song_groups as song_group
      where song_group.metadata_reference_song_id = new.id
        and song_group.id is distinct from new.song_group_id
    ) or exists (
      select 1 from public.song_group_origins as origin
      where origin.origin_song_id = new.id
        and origin.song_group_id is distinct from new.song_group_id
    ) then
      raise exception 'referenced song % cannot move outside its song_group without updating metadata/origin references', new.id;
    end if;
  end if;
  return new;
end;
$$;

create constraint trigger song_groups_metadata_reference_membership_check
after insert or update on public.song_groups
deferrable initially deferred for each row
execute function public.enforce_song_group_reference_membership();

create constraint trigger song_group_origins_membership_check
after insert or update on public.song_group_origins
deferrable initially deferred for each row
execute function public.enforce_song_group_reference_membership();

create constraint trigger songs_metadata_origin_membership_check
after update on public.songs
deferrable initially deferred for each row
execute function public.enforce_song_group_reference_membership();

alter table public.song_group_origins enable row level security;
revoke all privileges on table public.song_group_origins from anon, authenticated;
grant all privileges on table public.song_group_origins to service_role;
grant usage, select on sequence public.song_group_origins_id_seq to service_role;

commit;
