-- Live database draft for manual execution in the Supabase Dashboard SQL Editor.
-- This schema is performance-first: one live_performances row represents one
-- actual performance or stream. Parent events and series are optional relations.

begin;

-- Optional parent for genuinely grouped performances, such as a 2DAYS event.
create table public.live_event_groups (
  id bigint generated by default as identity primary key,
  title text not null,
  title_kana text,
  sort_title text,
  notes text,
  created_at timestamptz not null default now()
);

-- Public /live/[id] unit. streaming_platforms uses text[] as a lightweight,
-- multi-value field until platform normalization is demonstrably necessary.
create table public.live_performances (
  id bigint generated by default as identity primary key,
  live_event_group_id bigint references public.live_event_groups (id) on delete set null,
  group_sort_order integer,
  title text not null,
  title_kana text,
  sort_title text,
  artist_credit text,
  performance_date date,
  format_label text,
  image_url text,
  venue text,
  streaming_platforms text[] not null default '{}'::text[],
  notes text,
  published_at timestamptz,
  is_listed boolean not null default false,
  created_at timestamptz not null default now(),
  constraint live_performances_group_sort_order_check
    check (group_sort_order is null or group_sort_order > 0),
  constraint live_performances_listing_requires_publication_check
    check (is_listed = false or published_at is not null)
);

-- A series is independent from an event group. Anima and the Candy Live series
-- are examples; membership does not imply a parent/child event relationship.
create table public.live_series (
  id bigint generated by default as identity primary key,
  title text not null,
  title_kana text,
  sort_title text,
  notes text,
  created_at timestamptz not null default now()
);

create table public.live_series_members (
  id bigint generated by default as identity primary key,
  live_series_id bigint not null references public.live_series (id) on delete cascade,
  live_performance_id bigint not null references public.live_performances (id) on delete cascade,
  sort_order integer,
  created_at timestamptz not null default now(),
  constraint live_series_members_membership_unique
    unique (live_series_id, live_performance_id),
  constraint live_series_members_sort_order_check
    check (sort_order is null or sort_order > 0)
);

-- Songs and timeline markers share one ordered entry table so the UI and the
-- management workflow can treat a setlist as a single chronological sequence.
create table public.live_setlist_entries (
  id bigint generated by default as identity primary key,
  live_performance_id bigint not null references public.live_performances (id) on delete cascade,
  sort_order integer not null,
  entry_type text not null,
  setlist_no_raw text,
  song_id bigint references public.songs (id) on delete set null,
  song_title_raw text,
  artist_credit_raw text,
  note_raw text,
  marker_label text,
  notes text,
  joucho_participation boolean,
  created_at timestamptz not null default now(),
  constraint live_setlist_entries_performance_sort_order_unique
    unique (live_performance_id, sort_order),
  constraint live_setlist_entries_sort_order_check
    check (sort_order > 0),
  constraint live_setlist_entries_entry_type_check
    check (entry_type in ('song', 'marker')),
  constraint live_setlist_entries_entry_shape_check
    check (
      (
        entry_type = 'song'
        and song_title_raw is not null
        and btrim(song_title_raw) <> ''
        and marker_label is null
      )
      or
      (
        entry_type = 'marker'
        and marker_label is not null
        and btrim(marker_label) <> ''
        and song_id is null
        and setlist_no_raw is null
        and song_title_raw is null
        and artist_credit_raw is null
        and note_raw is null
        and joucho_participation is null
      )
    )
);

-- link_type intentionally remains free text. A small non-empty CHECK prevents
-- malformed rows without freezing an evolving official/archive/ticket vocabulary.
-- HTTP/HTTPS URL validation remains an application responsibility, as with links.
create table public.live_performance_links (
  id bigint generated by default as identity primary key,
  live_performance_id bigint not null references public.live_performances (id) on delete cascade,
  link_type text not null,
  label text,
  url text not null,
  published_date date,
  notes text,
  sort_order integer,
  created_at timestamptz not null default now(),
  constraint live_performance_links_performance_url_unique
    unique (live_performance_id, url),
  constraint live_performance_links_link_type_check
    check (btrim(link_type) <> ''),
  constraint live_performance_links_url_check
    check (btrim(url) <> ''),
  constraint live_performance_links_sort_order_check
    check (sort_order is null or sort_order > 0)
);

-- Import provenance. THINKR Wiki page_key is stored as source_key, not as a
-- public performance identifier. This table receives no public SELECT policy.
create table public.live_performance_sources (
  id bigint generated by default as identity primary key,
  live_performance_id bigint not null references public.live_performances (id) on delete cascade,
  source_type text,
  source_url text not null,
  source_key text,
  event_title_raw text,
  event_date_raw text,
  source_category_raw text,
  notes text,
  created_at timestamptz not null default now(),
  constraint live_performance_sources_performance_url_unique
    unique (live_performance_id, source_url),
  constraint live_performance_sources_url_check
    check (btrim(source_url) <> '')
);

-- Minimal indexes for the current public archive, relations, ordered setlist,
-- links and provenance lookups. The setlist UNIQUE constraint already provides
-- an index on (live_performance_id, sort_order).
create index live_performances_public_archive_idx
  on public.live_performances (performance_date desc, id desc)
  where published_at is not null and is_listed = true;

create index live_performances_event_group_idx
  on public.live_performances (live_event_group_id, group_sort_order, id)
  where live_event_group_id is not null;

create index live_series_members_series_order_idx
  on public.live_series_members (live_series_id, sort_order, id);

create index live_series_members_performance_idx
  on public.live_series_members (live_performance_id);

create index live_setlist_entries_song_idx
  on public.live_setlist_entries (song_id)
  where song_id is not null;

create index live_performance_links_performance_order_idx
  on public.live_performance_links (live_performance_id, sort_order, id);

-- RLS is explicit for every live table. Public roles can read published live
-- data only. Management writes continue through the service role.
alter table public.live_event_groups enable row level security;
alter table public.live_performances enable row level security;
alter table public.live_series enable row level security;
alter table public.live_series_members enable row level security;
alter table public.live_setlist_entries enable row level security;
alter table public.live_performance_links enable row level security;
alter table public.live_performance_sources enable row level security;

create policy live_performances_public_select
  on public.live_performances
  for select
  to anon, authenticated
  using (published_at is not null);

create policy live_event_groups_public_select
  on public.live_event_groups
  for select
  to anon, authenticated
  using (
    exists (
      select 1
      from public.live_performances as performance
      where performance.live_event_group_id = live_event_groups.id
        and performance.published_at is not null
    )
  );

create policy live_series_members_public_select
  on public.live_series_members
  for select
  to anon, authenticated
  using (
    exists (
      select 1
      from public.live_performances as performance
      where performance.id = live_series_members.live_performance_id
        and performance.published_at is not null
    )
  );

create policy live_series_public_select
  on public.live_series
  for select
  to anon, authenticated
  using (
    exists (
      select 1
      from public.live_series_members as member
      join public.live_performances as performance
        on performance.id = member.live_performance_id
      where member.live_series_id = live_series.id
        and performance.published_at is not null
    )
  );

create policy live_setlist_entries_public_select
  on public.live_setlist_entries
  for select
  to anon, authenticated
  using (
    exists (
      select 1
      from public.live_performances as performance
      where performance.id = live_setlist_entries.live_performance_id
        and performance.published_at is not null
    )
  );

create policy live_performance_links_public_select
  on public.live_performance_links
  for select
  to anon, authenticated
  using (
    exists (
      select 1
      from public.live_performances as performance
      where performance.id = live_performance_links.live_performance_id
        and performance.published_at is not null
    )
  );

-- Data API grants are explicit. No public mutation privileges are retained.
grant select on table
  public.live_event_groups,
  public.live_performances,
  public.live_series,
  public.live_series_members,
  public.live_setlist_entries,
  public.live_performance_links
to anon, authenticated;

revoke insert, update, delete, truncate, references, trigger on table
  public.live_event_groups,
  public.live_performances,
  public.live_series,
  public.live_series_members,
  public.live_setlist_entries,
  public.live_performance_links
from anon, authenticated;

-- Sources are deliberately unavailable through the public Data API.
revoke all privileges on table public.live_performance_sources
  from anon, authenticated;

-- The management client uses the service role. Grants are scoped to the seven
-- new tables and their identity sequences rather than the entire public schema.
grant all privileges on table
  public.live_event_groups,
  public.live_performances,
  public.live_series,
  public.live_series_members,
  public.live_setlist_entries,
  public.live_performance_links,
  public.live_performance_sources
to service_role;

grant usage, select on sequence
  public.live_event_groups_id_seq,
  public.live_performances_id_seq,
  public.live_series_id_seq,
  public.live_series_members_id_seq,
  public.live_setlist_entries_id_seq,
  public.live_performance_links_id_seq,
  public.live_performance_sources_id_seq
to service_role;

commit;
