-- Composite live-program entries, such as medleys and mashups.
--
-- A normal setlist row continues to use live_setlist_entries.song_id.  This
-- relation is intentionally only populated when one program entry comprises
-- multiple exact songs.

begin;

create table public.live_setlist_entry_songs (
  id bigint generated by default as identity primary key,
  live_setlist_entry_id bigint not null references public.live_setlist_entries (id) on delete cascade,
  song_id bigint not null references public.songs (id) on delete cascade,
  sort_order integer not null,
  role text,
  created_at timestamptz not null default now(),
  constraint live_setlist_entry_songs_entry_song_unique
    unique (live_setlist_entry_id, song_id),
  constraint live_setlist_entry_songs_sort_order_check
    check (sort_order > 0),
  constraint live_setlist_entry_songs_role_check
    check (role is null or btrim(role) <> '')
);

create index live_setlist_entry_songs_entry_order_idx
  on public.live_setlist_entry_songs (live_setlist_entry_id, sort_order, id);

create index live_setlist_entry_songs_song_idx
  on public.live_setlist_entry_songs (song_id);

alter table public.live_setlist_entry_songs enable row level security;

create policy live_setlist_entry_songs_public_select
  on public.live_setlist_entry_songs
  for select
  to anon, authenticated
  using (
    exists (
      select 1
      from public.live_setlist_entries as entry
      join public.live_performances as performance
        on performance.id = entry.live_performance_id
      where entry.id = live_setlist_entry_songs.live_setlist_entry_id
        and performance.published_at is not null
    )
  );

grant select on table public.live_setlist_entry_songs to anon, authenticated;

revoke insert, update, delete, truncate, references, trigger
  on table public.live_setlist_entry_songs
  from anon, authenticated;

grant select, insert, update, delete
  on table public.live_setlist_entry_songs
  to service_role;

grant usage, select on sequence public.live_setlist_entry_songs_id_seq
  to service_role;

commit;
