-- Additive edition/package component model for release tracklists.
-- release_groups remain release works/families; releases remain editions/packages.
-- Existing release_items.release_id stays the authoritative edition relation.

begin;

alter table public.releases
  add column release_kind text;

alter table public.releases
  add constraint releases_release_kind_nonempty_check
  check (release_kind is null or btrim(release_kind) <> '');

create table public.release_components (
  id bigint generated by default as identity primary key,
  release_id bigint not null
    references public.releases (id) on delete cascade,
  medium text not null,
  component_name text,
  component_number integer,
  catalog_number text,
  sort_order integer not null default 1,
  notes text,
  created_at timestamptz not null default now(),
  constraint release_components_medium_nonempty_check
    check (btrim(medium) <> ''),
  constraint release_components_component_number_check
    check (component_number is null or component_number > 0),
  constraint release_components_sort_order_check
    check (sort_order > 0),
  constraint release_components_release_sort_order_unique
    unique (release_id, sort_order)
);

alter table public.release_items
  add column release_component_id bigint
    references public.release_components (id) on delete restrict,
  add column sort_order integer;

alter table public.release_items
  add constraint release_items_sort_order_check
  check (sort_order is null or sort_order > 0);

create index release_components_release_order_idx
  on public.release_components (release_id, sort_order, id);
create index release_items_component_order_idx
  on public.release_items (release_component_id, sort_order, track_number, id);
create index release_items_release_order_idx
  on public.release_items (release_id, sort_order, disc_number, track_number, id);

-- A component can only be selected from the same edition/package as its item.
create function public.enforce_release_item_component_membership()
returns trigger
language plpgsql
as $$
begin
  if new.release_component_id is not null and not exists (
    select 1
    from public.release_components component
    where component.id = new.release_component_id
      and component.release_id = new.release_id
  ) then
    raise exception 'release_item component must belong to the same release';
  end if;

  return new;
end;
$$;

create trigger release_items_component_membership_trigger
  before insert or update of release_id, release_component_id
  on public.release_items
  for each row
  execute function public.enforce_release_item_component_membership();

create table public.release_sources (
  id bigint generated by default as identity primary key,
  release_id bigint not null
    references public.releases (id) on delete cascade,
  reference_source_id bigint not null
    references public.reference_sources (id) on delete restrict,
  locator text,
  evidence_note text,
  sort_order integer,
  created_at timestamptz not null default now(),
  constraint release_sources_release_source_unique
    unique (release_id, reference_source_id),
  constraint release_sources_sort_order_check
    check (sort_order is null or sort_order > 0)
);

create index release_sources_release_idx
  on public.release_sources (release_id, sort_order, id);
create index release_sources_source_idx
  on public.release_sources (reference_source_id);

comment on column public.releases.release_type is
  'Legacy mixed release type / medium display field. Keep for compatibility while release_kind becomes the work/package kind.';
comment on column public.releases.release_kind is
  'Canonical package kind. Recommended values: single, ep, album, compilation, live_album, video_release, other. Vocabulary intentionally remains extensible.';
comment on table public.release_components is
  'Physical or digital media components belonging to one release edition/package. Recommended medium values: digital, cd, blu_ray, dvd, other.';
comment on column public.release_items.release_id is
  'Authoritative edition/package containing this track/item.';
comment on column public.release_items.release_group_id is
  'Legacy release work/family relation retained for compatibility; not authoritative for edition tracklists.';
comment on column public.release_items.release_component_id is
  'Nullable component/disc/media containing this edition-specific item. NULL is allowed until component backfill or for unknown packaging.';
comment on column public.release_items.track_title is
  'Raw title printed by the release. Kept even when song_id is NULL.';
comment on column public.release_items.track_artist is
  'Raw artist credit printed by the release. Kept even when song_id is NULL.';
comment on table public.release_sources is
  'Private, ordered evidence relation from an edition/package to reusable reference source metadata.';

-- Release components are public metadata, consistent with releases and release_items.
alter table public.release_components enable row level security;
create policy release_components_public_select
  on public.release_components
  for select
  to anon, authenticated
  using (true);
revoke all privileges on table public.release_components from anon, authenticated;
grant select on table public.release_components to anon, authenticated;
grant all privileges on table public.release_components to service_role;
grant usage, select on sequence public.release_components_id_seq to service_role;

-- Reference relations remain management-only, like song_*_sources.
alter table public.release_sources enable row level security;
revoke all privileges on table public.release_sources from anon, authenticated;
grant all privileges on table public.release_sources to service_role;
grant usage, select on sequence public.release_sources_id_seq to service_role;

commit;
