-- Shared external-source metadata and exact song/version availability records.
-- Existing song_field_checks.evidence JSON remains untouched for staged adoption.

begin;

create table public.reference_sources (
  id bigint generated by default as identity primary key,
  url text not null unique,
  title text,
  publisher text,
  source_type text not null,
  published_at timestamptz,
  last_checked_at timestamptz,
  note text,
  created_at timestamptz not null default now(),
  constraint reference_sources_url_check
    check (btrim(url) <> ''),
  constraint reference_sources_source_type_check
    check (btrim(source_type) <> '')
);

create table public.song_field_check_sources (
  id bigint generated by default as identity primary key,
  song_field_check_id bigint not null
    references public.song_field_checks (id) on delete cascade,
  reference_source_id bigint not null
    references public.reference_sources (id) on delete restrict,
  locator text,
  evidence_note text,
  sort_order integer,
  created_at timestamptz not null default now(),
  constraint song_field_check_sources_check_source_unique
    unique (song_field_check_id, reference_source_id),
  constraint song_field_check_sources_sort_order_check
    check (sort_order is null or sort_order > 0)
);

create table public.song_availabilities (
  id bigint generated by default as identity primary key,
  song_id bigint not null references public.songs (id) on delete cascade,
  platform text not null,
  provider text,
  provider_scope text,
  access_type text not null,
  completeness text not null,
  content_type text not null,
  media_type text not null,
  access_url text,
  is_current boolean not null default true,
  checked_at timestamptz not null default now(),
  note text,
  created_at timestamptz not null default now(),
  constraint song_availabilities_platform_check
    check (btrim(platform) <> ''),
  constraint song_availabilities_access_type_check
    check (access_type in ('free', 'paid', 'members', 'other')),
  constraint song_availabilities_completeness_check
    check (completeness in ('full', 'partial', 'other')),
  constraint song_availabilities_content_type_check
    check (content_type in ('studio', 'live', 'other')),
  constraint song_availabilities_media_type_check
    check (media_type in ('video', 'audio', 'physical', 'other')),
  constraint song_availabilities_access_url_check
    check (access_url is null or btrim(access_url) <> '')
);

create table public.song_availability_sources (
  id bigint generated by default as identity primary key,
  song_availability_id bigint not null
    references public.song_availabilities (id) on delete cascade,
  reference_source_id bigint not null
    references public.reference_sources (id) on delete restrict,
  locator text,
  evidence_note text,
  sort_order integer,
  created_at timestamptz not null default now(),
  constraint song_availability_sources_availability_source_unique
    unique (song_availability_id, reference_source_id),
  constraint song_availability_sources_sort_order_check
    check (sort_order is null or sort_order > 0)
);

comment on table public.reference_sources is
  'Reusable metadata for external sources used as verification or availability evidence. Source URLs are normalized before storage.';
comment on table public.song_field_check_sources is
  'Ordered relation from append-only song field checks to reusable external sources.';
comment on table public.song_availabilities is
  'Current listening availability for an exact songs.id/version, independent of discovery_category.';
comment on table public.song_availability_sources is
  'Ordered evidence relation for exact song/version availability records.';

create index song_field_check_sources_check_idx
  on public.song_field_check_sources (song_field_check_id);
create index song_field_check_sources_source_idx
  on public.song_field_check_sources (reference_source_id);
create index song_availabilities_song_idx
  on public.song_availabilities (song_id);
create index song_availabilities_song_current_idx
  on public.song_availabilities (song_id, is_current);
create index song_availability_sources_availability_idx
  on public.song_availability_sources (song_availability_id);
create index song_availability_sources_source_idx
  on public.song_availability_sources (reference_source_id);

-- Management-only until source and availability views are explicitly published.
alter table public.reference_sources enable row level security;
alter table public.song_field_check_sources enable row level security;
alter table public.song_availabilities enable row level security;
alter table public.song_availability_sources enable row level security;

revoke all privileges on table public.reference_sources,
  public.song_field_check_sources,
  public.song_availabilities,
  public.song_availability_sources
  from anon, authenticated;

grant all privileges on table public.reference_sources,
  public.song_field_check_sources,
  public.song_availabilities,
  public.song_availability_sources
  to service_role;

grant usage, select on sequence public.reference_sources_id_seq,
  public.song_field_check_sources_id_seq,
  public.song_availabilities_id_seq,
  public.song_availability_sources_id_seq
  to service_role;

commit;
